name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - name: make tests
        run: make all
      - name: Generate HTML Report
        uses: threeal/gcovr-action@v1.1.0
        with:
          html-out: coverage.html
          html-details: true
          html-title: My Project Test Coverage Report
          html-theme: github.green
