name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - name: make tests
        run: make all
      - name: Generate a code coverage report
        uses: threeal/gcovr-action@v1.0.0
        with:
          xml-out: coverage.xml
